### ISSUE TITLE
有没有打好了的Parcel包？

### ISSUE THREAD

**Issue by 2416210017** [ZhanHui-Xu/zookeeper-parcel#1]
运行脚本多个地方报错，service.sdl格式错误，请问有打好的包吗？方便分享一下吗？谢谢！
![image](https://user-images.githubusercontent.com/52597892/206902885-f79f6868-2877-40b1-b972-f578a91b8707.png)

**Comment by hongming-xu** [comment]
也没打好，打包脚本还有些问题，最后是直接替换cloudera 的zk jar包.

**Comment by hongming-xu** [comment]
打包脚本还有些问题，直接替换cloudera 下的 zk jar包试试.

**Comment by ZhanHui-Xu** [comment]
打包脚本还有些问题，直接替换cloudera 下的 zk jar包试试.

**Comment by 2416210017** [comment]
> 打包脚本还有些问题，直接替换cloudera 下的 zk jar包试试.

那样不行，我们生产环境现在cdh自带的zookeeper目前有在使用，主要是直接替换升级怕会影响自带的集群会不兼容；目前考虑新版本升级是因为flink需要开启ha特性（Flink_1.1.5不支持cdh自带的zookeeper_3.4.5）；所以要打一个新版本zookeeper_parcels来支持flink_ha特性；

![image](https://user-images.githubusercontent.com/52597892/206955476-7a9bc3cb-ff0f-414c-b392-5bf933d5102a.png)

--

 _**感谢你的回复，这边看下能不能自己打一个zookeeper的parcels。**_
